export const styles = {
  content: {
    display: "flex",
    justifyContent: "center",
    fontFamily: "Helvetica, sans-serif",
    color: "#fff",
    marginTop: "130px",
    padding: "10px",
  },
  header: {
    position: "fixed",
    zIndex: 1,
    width: "100%",
    background: "#000",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    fontFamily: "Helvetica, sans-serif",
    borderBottom: "2px solid rgba(0, 0, 0, 0.06)",
    // padding: "0 10px",
    boxShadow: "0 1px 10px rgb(151 164 175 / 10%)",
  },
  header2: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "5px",
  },
  headerRight: {
    display: "flex",
    gap: "20px",
    alignItems: "center",
    fontSize: "15px",
    fontWeight: "600",
  },
  title: {
    fontSize: "30px",
    fontWeight: "600",
  },
  card: {
    background: "#212124",
    border: "1px solid #46464D",
    borderRadius: "1rem",
    width: "450px",
  },
  headerRentBike: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "5px",

  },
  text: {
    fontSize: "16px",
    color: "#fff",
    fontWeight: "400",
  },
  timeline: {
    marginBottom: "-45px",
  },
  link: {
    color: "#9b84ec",
    fontSize: "16px",
    fontWeight: "600",
  },
  account: {
    height: "42px",
    padding: "0 15px",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "fit-content",
    borderRadius: "12px",
    backgroundColor: "rgb(244, 244, 244)",
    cursor: "pointer",
  },
  accountText: {
    color: "#f37b68",
  },
  connector: {
    alignItems: "center",
    display: "flex",
    flexDirection: "column",
    height: "auto",
    justifyContent: "center",
    marginLeft: "auto",
    marginRight: "auto",
    padding: "20px 5px",
    cursor: "pointer",
  },
  icon: {
    alignSelf: "center",
    fill: "rgb(40, 13, 95)",
    flexShrink: "0",
    marginBottom: "8px",
    height: "30px",
  },
  menu: {
    display: "flex",
    fontSize: "17px",
    fontWeight: "500",
    width: "100%",
    justifyContent: "center",
  },
  tabLink: {
    color: "#abcdff",
    fontSize: "20px",
  },
  headerRenter: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    color: "#fff",
    gap: "15px",
  },
  item: {
    display: "flex",
    alignItems: "center",
    height: "42px",
    fontWeight: "500",
    fontFamily: "Helvetica, sans-serif",
    fontSize: "14px",
    padding: "0 10px",
  },
  button: {
    color: "#fff",
    background: "#4D516B",
    border: "1px solid #8EA8D4",
    borderRadius: "5px",
  },
  NFTs: {
    display: "flex",
    flexWrap: "wrap",
    WebkitBoxPack: "start",
    justifyContent: "flex-start",
    margin: "0 auto",
    maxWidth: "1000px",
    width: "100%",
    gap: "10px",
  },
  headerRentee: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: "5px",
  },
  address: {
    height: "36px",
    display: "flex",
    gap: "5px",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: "9px",
    alignItems: "center",
  },
  token: {
    padding: "0 7px",
    height: "42px",
    gap: "5px",
    width: "fit-content",
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    whiteSpace: "nowrap",
  },
  input: {
    padding: "0",
    fontWeight: "500",
    fontSize: "23px",
    display: "block",
    width: "100%",
  },
  priceSwap: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: "15px",
    color: "#434343",
    marginTop: "8px",
    padding: "0 10px",
  },
  cardTransfer: {
    alignItems: "center",
    width: "100%",
  },
  headerTransfer: {
    textAlign: "center",
  },
  select: {
    marginTop: "20px",
    display: "flex",
    alignItems: "center",
  },
  textWrapper: {
    maxWidth: "80px",
    width: "100%",
  },
  row: {
    display: "flex",
    alignItems: "center",
    gap: "10px",
    flexDirection: "row",
  },
};
